apiVersion: v1
kind: Secret
metadata:
  name: azure-log-storage-account
type: Opaque
data:
  azurestorageaccountname: Y2FudmFzc3Byb2RjY2Fu
  azurestorageaccountkey: T2hTTDJ0MS91VzJ3U2lVTnRJRm5Vck16b2tPNmNKcGxOb0U0NlI0SFY1RkVtTDNjb3NobVFHeFZ6NlJuMHdIeEhPem1HMzAxSUFYbExraGczUzRaQ3c9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit
type: Opaque
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: api
type: Opaque
data:
  username: YWRtaW4=
  password: ZGF0dWhNTDRhbGwh
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  hostname: Y2FudmFzc3Byb2RjY2FuLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  username: ZGF0dWhtbEBjYW52YXNzcHJvZGNjYW4=
  password: YWxsNE1MaHV0YWQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: webserver
type: Opaque
data:
  dns: Y2FudmFzcy5jYW5hZGFjZW50cmFsLmNsb3VkYXBwLmF6dXJlLmNvbQ==
  ##############################
  ##---         NIFI       ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nifi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: canvass.azurecr.io/nifi:latest
        env:
          - name: BANNER_TEXT
            value: 'Canvass Flow'
        volumeMounts:
          - name: repo
            mountPath: /repo
          - name: nifi-logs
            mountPath: /opt/nifi/logs
          - name: nifi-datafiles
            mountPath: /opt/datafiles
          - name: nifi-certfiles
            mountPath: /opt/certfiles
        ports:
        - containerPort: 8080
          name: nifi-web
        - containerPort: 8081
          name: nifi-proc-port
        - containerPort: 8443
          name: nifi-web-secure
      volumes:
        - name: repo
          azureFile:
            secretName: azure-log-storage-account
            shareName: nifi-repo
            readOnly: False
        - name: nifi-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: False
        - name: nifi-datafiles
          azureFile:
            secretName: azure-log-storage-account
            shareName: nifi-datafiles
            readOnly: False
        - name: nifi-certfiles
          azureFile:
            secretName: azure-log-storage-account
            shareName: nifi-certfiles
            readOnly: False
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-web
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    name: nifi-web
  selector:
    app: nifi
  loadBalancerSourceRanges:
  - 66.207.193.114/32
