apiVersion: v1
kind: Secret
metadata:
  name: azure-log-storage-account
type: Opaque
data:
  azurestorageaccountname: Y2FudmFzc3Byb2RjY2Fu
  azurestorageaccountkey: ZFIwVitWK3F1amJRWHJyclBZek9zcHBoRk9EWEt3c0lPRTBrbjJ1NjhsWXN4bVNqaU5oVmtYbVluR0xmMVM5SktGbFM2b043N1htOE9jZmUreWV1TGc9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit
type: Opaque
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: api
type: Opaque
data:
  username: YWRtaW4=
  password: ZGF0dWhNTDRhbGwh
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  hostname: Y2FudmFzc3Byb2RjY2FuLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  username: ZGF0dWhtbEBjYW52YXNzcHJvZGNjYW4=
  password: YWxsNE1MaHV0YWQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: webserver
type: Opaque
data:
  dns: Y2FudmFzcy5jYW5hZGFjZW50cmFsLmNsb3VkYXBwLmF6dXJlLmNvbQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: hbase
type: Opaque
data:
  local_ip: MTAuMy4wLjE0
