apiVersion: v1
kind: Secret
metadata:
  name: azure-log-storage-account
type: Opaque
data:
  azurestorageaccountname: Y2FudmFzc2RlbW9jY2Fu
  azurestorageaccountkey: Yy90d3FTdFQ3VFQ2ODZDSGNXV2tSYnNLQzV4enU3R3A5QmdvS08vK08wWGZlaStWR2hRemMxVlRwNGhFaDBIMXgyd2dyVVdZZWdIU2VlZ0VobWJUaXc9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit
type: Opaque
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: api
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  hostname: Y2FudmFzc2RlbW9jY2FuLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  username: ZGF0dWhtbEBjYW52YXNzZGVtb2NjYW4=
  password: YWxsNE1MaHV0YWQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: webserver
type: Opaque
data:
  dns: Y2FudmFzc2RlbW8uY2FuYWRhY2VudHJhbC5jbG91ZGFwcC5henVyZS5jb20=
