apiVersion: v1
kind: Secret
metadata:
  name: log-storage-account
type: Opaque
data:
  azurestorageaccountname:
  azurestorageaccountkey:
---
kind: Secret
metadata:
  name: rabbit
type: Opaque
data:
  username:
  password:
---
kind: Secret
metadata:
  name: api
type: Opaque
data:
  username:
  password:
---
kind: Secret
metadata:
  name: hbase
type: Opaque
data:
  hostname:
