version: "3"

services:
  hbase:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: hbase
    ports:
      - "8080:8080" # REST API
      - "8085:8085" # REST Web UI at :8085/rest.jsp
      - "9090:9090" # Thrift API
      - "9095:9095" # Thrift Web UI at :9095/thrift.jsp
      - "2181:2181" # Embedded zookeeper cluster
      - "16010:16010" # HBase Master Web UI at :16010/master-status; ZK at :16010/zk.jsp
    volumes:
      - /data/hbase:/data
