version: '2'

services:

  # pyml server
  ml:
    image: datuh/pyml:1.0
    hostname: ml
    environment:
      RABBIT_PORT_6372_TCP: '10.3.0.4' # Use VLAN IP to avoid going outside the network
      RABBIT_ENV_USER: 'guest'
      RABBIT_ENV_PASS: 'guest'
      RABBIT_ENV_VHOST: ''
      API_HOSTNAME: 'prodweb01.northcentralus.cloudapp.azure.com'
      API_USERNAME: 'admin'
      API_PASSWORD: 'datuhML4all!'
      HBASE_PORT_9090_TCP: '10.3.0.14'
    volumes:
      - ~/data/pyml/logs:/app/logs
      - ~/data/pyml/files:/app/files
