  ##############################
  ##---    AIInterpret     ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aiinterpret
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aiinterpret
    spec:
      containers:
      - name: aiinterpret
        image: canvass.azurecr.io/aiinterpret
        env:
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: API_HOSTNAME
            value: 'web:8001'
          - name: RABBIT_ENV_USER
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: username
          - name: RABBIT_ENV_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: password
          - name: API_USERNAME
            valueFrom:
              secretKeyRef:
                name: api
                key: username
          - name: API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api
                key: username
        volumeMounts:
          - name: aiinterpret-logs
            mountPath: /app/logs
          - name: pyml-files
            mountPath: /app/files
        resources:
          requests:
            cpu: .2
          limits:
            cpu: 4
      volumes:
        - name: aiinterpret-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: false
        - name: pyml-files
          azureFile:
            secretName: azure-log-storage-account
            shareName: pyml
            readOnly: false
