  # #############################
  # #---    AIInterpret     ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aiinterpret
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aiinterpret
    spec:
      containers:
      - name: aiinterpret
        image: canvass.azurecr.io/aiinterpret
        env:
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: RABBIT_ENV_USER
            value: 'guest'
          - name: RABBIT_ENV_PASS
            value: 'guest'
          - name: API_HOSTNAME
            value: 'web:8001'
          - name: API_USERNAME
            value: 'admin'
          - name: API_PASSWORD
            value: 'password123'
          - name: HBASE_PORT_9090_TCP
            value: '10.4.2.18'
        volumeMounts:
          - name: aiinterpret-logs
            mountPath: /app/aiinterpret/logs
        resources:
          requests:
            cpu: .2
          limits:
            cpu: 4
      volumes:
        - name: aiinterpret-logs
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: logs
            readOnly: false
---
