  ##############################
  ##---         NIFI       ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nifi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: canvass.azurecr.io/nifi:optimization
        env:
          - name: BANNER_TEXT
            value: 'Canvass Flow'
        volumeMounts:
          - name: repo
            mountPath: /repo
          - name: flow-config
            mountPath: /flowfile
          - name: nifi-logs
            mountPath: /opt/nifi/logs
          - name: nifi-datafiles
            mountPath: /opt/datafiles
          - name: nifi-certfiles
            mountPath: /opt/certfiles
        ports:
        - containerPort: 8080
          name: nifi-web
        - containerPort: 8081
          name: nifi-proc-port
        - containerPort: 8443
          name: nifi-web-secure
      volumes:
        - name: repo
          azureFile:
            secretName: azure-log-storage-account
            shareName: nifi-repo
            readOnly: False
        - name: flow-config
          azureFile:
            secretName: azure-log-storage-account
            shareName: nifi-flowconfig
            readOnly: False
        - name: nifi-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: False
        - name: nifi-datafiles
          azureFile:
            secretName: azure-log-storage-account
            shareName: nifi-datafiles
            readOnly: False
        - name: nifi-certfiles
          azureFile:
            secretName: azure-log-storage-account
            shareName: nifi-certfiles
            readOnly: False
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-web
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    name: nifi-web
  selector:
    app: nifi
  loadBalancerSourceRanges:
  - 66.207.193.114/32
