  # #############################
  # #---        pyML        ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ml
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
      - name: ml
        image: canvass.azurecr.io/pyml
        env:
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: RABBIT_ENV_USER
            value: 'guest'
          - name: RABBIT_ENV_PASS
            value: 'guest'
          - name: API_HOSTNAME
            value: 'web:8001'
          - name: API_USERNAME
            value: 'admin'
          - name: API_PASSWORD
            value: 'password123'
          - name: HBASE_PORT_9090_TCP
            value: hbase-cluster
        volumeMounts:
          - name: ml-logs
            mountPath: /app/logs
          - name: ml-files
            mountPath: /app/files
        resources:
          requests:
            cpu: .2
          limits:
            cpu: 4
      volumes:
        - name: ml-logs
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: logs
            readOnly: false
        - name: ml-files
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: pyml
            readOnly: false
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ml-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: ml
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
kind: Service
apiVersion: v1
metadata:
  name: hbase-cluster
spec:
  ports:
  - port: 9090
---
kind: Endpoints
apiVersion: v1
metadata:
  name: hbase-cluster
subsets:
  - addresses:
      - ip: 10.4.2.18
    ports:
      - port: 9090
