version: '2'

services:
  # Redis
  redis:
    image: redis:3.0
    hostname: redis
    volumes_from:
      - reddata
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/data/rabbitmq-persist:/var/lib/rabbitmq

  # Django web server
  web:
    image: datuh/datuhweb:latest
    hostname: web
    environment:
      POSTGRES_PORT_5432_TCP: 'datuhpreprod.postgres.database.azure.com'
      POSTGRES_DB_USERNAME: 'datuhml@datuhpreprod'
      POSTGRES_DB_PASSWORD: 'all4MLhutad'
      SERVER_HOST_NAME: 'preprodweb01.northcentralus.cloudapp.azure.com' # Add the DNS or IP that will be used to connect to the website
      RABBIT_PORT_6372_TCP: 'rabbit'
      RABBIT_ENV_USER: 'guest'
      RABBIT_ENV_RABBITMQ_PASS: 'guest'
      RABBIT_ENV_VHOST: ''
      REDIS_URL: 'redis://redis:6379'
    volumes:
      - ~/data/django-media:/app/media
    command: ./run_web.sh
    ports:
      - "8000:8000"
    links:
      - rabbit
      - redis

  # Celery worker
  worker:
    image: datuh/datuhweb:latest
    hostname: worker
    environment:
      RABBIT_PORT_6372_TCP: 'rabbit'
      POSTGRES_PORT_5432_TCP: 'datuhpreprod.postgres.database.azure.com'
      POSTGRES_DB_USERNAME: 'datuhml@datuhpreprod'
      POSTGRES_DB_PASSWORD: 'all4MLhutad'
    volumes:
      - ~/data/django-media:/app/media
    entrypoint: ./run_celery.sh
    links:
      - rabbit

  # Redis Data Container
  reddata:
    image: cogniteev/echo
    command: echo 'Data Container for Redis'
    volumes:
      - ~/data/redis:/data
