  # #############################
  # #---        pyML        ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ml
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
      - name: ml
        image: canvass.azurecr.io/pyml
        env:
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: RABBIT_ENV_USER
            value: 'guest'
          - name: RABBIT_ENV_PASS
            value: 'guest'
          - name: API_HOSTNAME
            value: 'web:8000'
          - name: API_USERNAME
            value: 'admin'
          - name: API_PASSWORD
            value: 'password123'
          - name: HBASE_PORT_9090_TCP
            value: '10.4.2.18'
        volumeMounts:
          - name: ml-logs
            mountPath: /app/logs
          - name: ml-files
            mountPath: /app/files
        resources:
          requests:
            cpu: .2
          limits:
            cpu: 4
      volumes:
        - name: ml-logs
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: logs
            readOnly: false
        - name: ml-files
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: pyml
            readOnly: false
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ml-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: ml
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
  # #############################
  # #---      RabbitMQ      ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3-management
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: 'guest'
          - name: RABBITMQ_DEFAULT_PASS
            value: 'guest'
          - name: RABBITMQ_LOG_BASE
            value: '/var/log/canvass/rabbitmq'
        volumeMounts:
          - name: rabbit-logs
            mountPath: /var/log/canvass/rabbitmq
        ports:
        - containerPort: 15672
          name: rabbit-mgmt
        - containerPort: 5672
          name: rabbit
      volumes:
        - name: rabbit-logs
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: logs
            readOnly: False
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mgmt
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 15672
    name: rabbit-mgmt
  selector:
    app: rabbit
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  ports:
  - protocol: TCP
    port: 5672
    name: rabbit
  selector:
    app: rabbit
---
  # #############################
  # #---       Redis        ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.0
        volumeMounts:
          - name: redis
            mountPath: /data
        ports:
        - containerPort: 6379
          name: redis
      volumes:
        - name: redis
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: redis
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - protocol: TCP
    port: 6379
    name: redis
  selector:
    app: redis
---
  # #############################
  # #---  Daphne Webserver  ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: canvass.azurecr.io/datuhweb:feature-issue_51_centeralized_logging
        env:
          - name: ENVIROMENT
            value: 'DEVELOP'
          - name: POSTGRES_PORT_5432_TCP
            value: 'canvassdev.postgres.database.azure.com'
          - name: POSTGRES_DB_USERNAME
            value: 'datuhml@canvassdev'
          - name: POSTGRES_DB_PASSWORD
            value: 'all4MLhutad'
          - name: SERVER_HOST_NAME
            value: 'canvassdevk801.canadacentral.cloudapp.azure.com'
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: RABBIT_ENV_USER
            value: 'guest'
          - name: RABBIT_ENV_RABBITMQ_PASS
            value: 'guest'
          - name: REDIS_URL
            value: 'redis://redis:6379'
          - name: LOG_VOLUME_CELERY
            value: '/var/log/canvass/celery'
          - name: LOG_VOLUME_DATUHWEB
            value: '/var/log/canvass/datuhweb'
        command: ["/bin/sh","-c"]
        args: ["daphne -b 0.0.0.0 -p 8001 datuhweb.asgi:channel_layer --access-log=${LOG_VOLUME_DATUHWEB}/daphne.access.log"]
        volumeMounts:
          - name: web-logs
            mountPath: /var/log/canvass/datuhweb
          - name: web-media
            mountPath: /app/media
        ports:
        - containerPort: 8001
          name: web
      volumes:
        - name: web-logs
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: logs
            readOnly: False
        - name: web-media
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: web
            readOnly: False
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - protocol: TCP
    port: 8001
    name: web
  selector:
    app: web
---
  # #############################
  # #---   Daphne Worker    ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: daphne-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: daphne-worker
    spec:
      containers:
      - name: daphne-worker
        image: canvass.azurecr.io/datuhweb:feature-issue_51_centeralized_logging
        env:
          - name: ENVIROMENT
            value: 'DEVELOP'
          - name: POSTGRES_PORT_5432_TCP
            value: 'canvassdev.postgres.database.azure.com'
          - name: POSTGRES_DB_USERNAME
            value: 'datuhml@canvassdev'
          - name: POSTGRES_DB_PASSWORD
            value: 'all4MLhutad'
          - name: SERVER_HOST_NAME
            value: 'canvassdevk801.canadacentral.cloudapp.azure.com'
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: RABBIT_ENV_USER
            value: 'guest'
          - name: RABBIT_ENV_RABBITMQ_PASS
            value: 'guest'
          - name: REDIS_URL
            value: 'redis://redis:6379'
          - name: LOG_VOLUME_CELERY
            value: '/var/log/canvass/celery'
          - name: LOG_VOLUME_DATUHWEB
            value: /var/log/canvass/datuhweb
        command: ["./compose/daphne/run_web.sh"]
        volumeMounts:
          - name: web-logs
            mountPath: /var/log/canvass/datuhweb
          - name: web-media
            mountPath: /app/media
      volumes:
        - name: web-logs
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: logs
            readOnly: False
        - name: web-media
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: web
            readOnly: False
---
  # #############################
  # #---   Daphne Worker    ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: canvass.azurecr.io/datuhweb:feature-issue_51_centeralized_logging
        env:
          - name: ENVIROMENT
            value: 'DEVELOP'
          - name: POSTGRES_PORT_5432_TCP
            value: 'canvassdev.postgres.database.azure.com'
          - name: POSTGRES_DB_USERNAME
            value: 'datuhml@canvassdev'
          - name: POSTGRES_DB_PASSWORD
            value: 'all4MLhutad'
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: RABBIT_ENV_USER
            value: 'guest'
          - name: RABBIT_ENV_RABBITMQ_PASS
            value: 'guest'
          - name: LOG_VOLUME_CELERY
            value: '/var/log/canvass/celery'
          - name: LOG_VOLUME_DATUHWEB
            value: /var/log/canvass/datuhweb
        command: ["./compose/celery/run_celery.sh"]
        volumeMounts:
          - name: web-logs
            mountPath: /var/log/canvass/celery
          - name: web-media
            mountPath: /app/media
      volumes:
        - name: web-logs
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: logs
            readOnly: False
        - name: web-media
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: web
            readOnly: False
---
  # #############################
  # #---      Ngnix         ---##
  # #############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: canvass.azurecr.io/nginx
        volumeMounts:
          - name: nginx-logs
            mountPath: /var/log/canvass/nginx
        ports:
        - containerPort: 80
          name: web
      volumes:
        - name: nginx-logs
          azureFile:
            secretName: devkub01-devkubcluster01-3029b6mgmt.canadacentral.cloudapp.azure.com
            shareName: logs
            readOnly: False
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    name: nginx
  selector:
    app: nginx
