  ##############################
  ##---        pyML        ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ml
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
      - name: ml
        image: canvass.azurecr.io/pyml
        env:
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: RABBIT_ENV_USER
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: username
          - name: RABBIT_ENV_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: password
          - name: API_HOSTNAME
            value: 'web:8001'
          - name: API_USERNAME
            valueFrom:
              secretKeyRef:
                name: api
                key: username
          - name: API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api
                key: username
          - name: HBASE_PORT_9090_TCP
            value: hbase-cluster
        volumeMounts:
          - name: ml-logs
            mountPath: /app/logs
          - name: ml-files
            mountPath: /app/files
        resources:
          requests:
            cpu: .2
          limits:
            cpu: 4
      volumes:
        - name: ml-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: false
        - name: ml-files
          azureFile:
            secretName: azure-log-storage-account
            shareName: pyml
            readOnly: false
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ml-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: ml
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
kind: Service
apiVersion: v1
metadata:
  name: hbase-cluster
spec:
  ports:
  - port: 9090
---
kind: Endpoints
apiVersion: v1
metadata:
  name: hbase-cluster
subsets:
  - addresses:
      - ip: 10.4.2.18
    ports:
      - port: 9090
---
  ##############################
  ##---    AIInterpret     ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aiinterpret
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aiinterpret
    spec:
      containers:
      - name: aiinterpret
        image: canvass.azurecr.io/aiinterpret
        env:
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: API_HOSTNAME
            value: 'web:8001'
          - name: RABBIT_ENV_USER
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: username
          - name: RABBIT_ENV_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: password
          - name: API_USERNAME
            valueFrom:
              secretKeyRef:
                name: api
                key: username
          - name: API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api
                key: username
        volumeMounts:
          - name: aiinterpret-logs
            mountPath: /app/logs
        resources:
          requests:
            cpu: .2
          limits:
            cpu: 4
      volumes:
        - name: aiinterpret-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: false
---
  ##############################
  ##---      RabbitMQ      ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3-management
        env:
          - name: RABBIT_ENV_USER
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: username
          - name: RABBIT_ENV_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: password
          - name: RABBITMQ_LOG_BASE
            value: '/var/log/canvass/rabbitmq'
        volumeMounts:
          - name: rabbit-logs
            mountPath: /var/log/canvass/rabbitmq
        ports:
        - containerPort: 15672
          name: rabbit-mgmt
        - containerPort: 5672
          name: rabbit
      volumes:
        - name: rabbit-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: False
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mgmt
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 15672
    name: rabbit-mgmt
  selector:
    app: rabbit
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  ports:
  - protocol: TCP
    port: 5672
    name: rabbit
  selector:
    app: rabbit
---
  ##############################
  ##---       Redis        ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.0
        volumeMounts:
          - name: redis
            mountPath: /data
        ports:
        - containerPort: 6379
          name: redis
      volumes:
        - name: redis
          azureFile:
            secretName: azure-log-storage-account
            shareName: redis
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - protocol: TCP
    port: 6379
    name: redis
  selector:
    app: redis
---
  ##############################
  ##---  Daphne Webserver  ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: canvass.azurecr.io/datuhweb:f68bec4-develop
        env:
          - name: ENVIROMENT
            value: 'DEVELOP'
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: REDIS_URL
            value: 'redis://redis:6379'
          - name: RABBIT_ENV_USER
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: username
          - name: RABBIT_ENV_RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: password
          - name: POSTGRES_PORT_5432_TCP
            valueFrom:
              secretKeyRef:
                name: postgres
                key: hostname
          - name: POSTGRES_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: SERVER_HOST_NAME
            valueFrom:
              secretKeyRef:
                name: webserver
                key: dns
          - name: LOG_VOLUME_CELERY
            value: '/var/log/canvass/celery'
          - name: LOG_VOLUME_DATUHWEB
            value: '/var/log/canvass/datuhweb'
        command: ["./compose/daphne/run_web.sh"]
        volumeMounts:
          - name: web-logs
            mountPath: /var/log/canvass/datuhweb
          - name: web-media
            mountPath: /app/media
        ports:
        - containerPort: 8001
          name: web
      volumes:
        - name: web-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: False
        - name: web-media
          azureFile:
            secretName: azure-log-storage-account
            shareName: web
            readOnly: False
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
    name: web
  selector:
    app: web
---
  ##############################
  ##---   Daphne Worker    ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: daphne-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: daphne-worker
    spec:
      containers:
      - name: daphne-worker
        image: canvass.azurecr.io/datuhweb:f68bec4-develop
        env:
          - name: ENVIROMENT
            value: 'DEVELOP'
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: REDIS_URL
            value: 'redis://redis:6379'
          - name: RABBIT_ENV_USER
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: username
          - name: RABBIT_ENV_RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: password
          - name: POSTGRES_PORT_5432_TCP
            valueFrom:
              secretKeyRef:
                name: postgres
                key: hostname
          - name: POSTGRES_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: SERVER_HOST_NAME
            valueFrom:
              secretKeyRef:
                name: webserver
                key: dns
          - name: LOG_VOLUME_CELERY
            value: '/var/log/canvass/celery'
          - name: LOG_VOLUME_DATUHWEB
            value: /var/log/canvass/datuhweb
        command: ["/bin/sh","-c"]
        args: ["python -u manage.py runworker -v2"]
        volumeMounts:
          - name: web-logs
            mountPath: /var/log/canvass/datuhweb
          - name: web-media
            mountPath: /app/media
      volumes:
        - name: web-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: False
        - name: web-media
          azureFile:
            secretName: azure-log-storage-account
            shareName: web
            readOnly: False
---
  ##############################
  ##---   Celery Worker    ---##
  ##############################
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: canvass.azurecr.io/datuhweb:f68bec4-develop
        env:
          - name: ENVIROMENT
            value: 'DEVELOP'
          - name: RABBIT_PORT_6372_TCP
            value: 'rabbit'
          - name: RABBIT_ENV_USER
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: username
          - name: RABBIT_ENV_RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit
                key: password
          - name: POSTGRES_PORT_5432_TCP
            valueFrom:
              secretKeyRef:
                name: postgres
                key: hostname
          - name: POSTGRES_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: SERVER_HOST_NAME
            valueFrom:
              secretKeyRef:
                name: webserver
                key: dns
          - name: LOG_VOLUME_CELERY
            value: '/var/log/canvass/celery'
          - name: LOG_VOLUME_DATUHWEB
            value: /var/log/canvass/datuhweb
        command: ["./compose/celery/run_celery.sh"]
        volumeMounts:
          - name: web-logs
            mountPath: /var/log/canvass/celery
          - name: web-media
            mountPath: /app/media
      volumes:
        - name: web-logs
          azureFile:
            secretName: azure-log-storage-account
            shareName: logs
            readOnly: False
        - name: web-media
          azureFile:
            secretName: azure-log-storage-account
            shareName: web
            readOnly: False