version: '2'

services:
  # PostgreSQL database
  db:
    image: postgres:9.6.3
    environment:
      POSTGRES_DB: 'datuhml'
      POSTGRES_USER: 'datuhmluser'
      POSTGRES_PASSWORD: 'datuhML4all!'
    volumes:
      - ~/data/postgresql-persist:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:3.0
    hostname: redis
    volumes_from:
      - reddata
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/data/rabbitmq-persist:/var/lib/rabbitmq

  # Django web server
  web:
    image: canvass/datuhweb:1.1
    hostname: web
    environment:
      POSTGRES_PORT_5432_TCP: 'db'
      SERVER_HOST_NAME: '10.203.0.167' # Add the DNS or IP that will be used to connect to the website
      RABBIT_PORT_6372_TCP: 'rabbit'
      RABBIT_ENV_USER: 'guest'
      RABBIT_ENV_RABBITMQ_PASS: 'guest'
      RABBIT_ENV_VHOST: ''
      REDIS_URL: 'redis://redis:6379'
    volumes:
      - ~/data/django-media:/app/media
    command: ./run_web.sh
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db
      - redis

  # Celery worker
  worker:
    image: canvass/datuhweb:1.1
    hostname: worker
    environment:
      RABBIT_PORT_6372_TCP: 'rabbit'
      POSTGRES_PORT_5432_TCP: 'db'
    volumes:
      - ~/data/django-media:/app/media
    entrypoint: ./run_celery.sh
    links:
      - db
      - rabbit
    depends_on:
      - db

  # Hbase Server
  hbase:
    image: canvass/hbase-docker:1
    hostname: hbase
    ports:
      - "8080:8080" # REST API
      - "8085:8085" # REST Web UI at :8085/rest.jsp
      - "9090:9090" # Thrift API
      - "9095:9095" # Thrift Web UI at :9095/thrift.jsp
      - "2181:2181" # Embedded zookeeper cluster
      - "16010:16010" # HBase Master Web UI at :16010/master-status; ZK at :16010/zk.jsp
    volumes:
      - ~/data/hbase:/data

  # pyml server
  ml:
    image: canvass/pyml:1.1
    hostname: ml
    environment:
      RABBIT_PORT_6372_TCP: 'rabbit'
      RABBIT_ENV_USER: 'guest'
      RABBIT_ENV_PASS: 'guest'
      RABBIT_ENV_VHOST: ''
      # BROKER_URL: 'amqp://{user}:{password}@{hostname}/{vhost}'
      API_HOSTNAME: 'web:8000'
      API_USERNAME: 'admin'
      API_PASSWORD: 'password123'
      HBASE_PORT_9090_TCP: 'hbase'
    volumes:
      - ~/data/pyml/logs:/app/logs
      - ~/data/pyml/files:/app/files

  # NIFI Server
  nifi:
    image: canvass/nifi:1.0
    hostname: nifi
    environment:
      BANNER_TEXT: 'DAT-UH Flow'
    volumes:
      - ~/data/nifi/logs:/opt/nifi/logs
      - ~/data/nifi/flowfile_repository:/opt/nifi/flowfile_repository
      - ~/data/nifi/database_repository:/opt/nifi/database_repository
      - ~/data/nifi/content_repository:/opt/nifi/content_repository
      - ~/data/nifi/provenance_repository:/opt/nifi/provenance_repository
      - ~/data/nifi/conf/archive:/opt/nifi/conf/archive
      - ~/data/nifi/datafiles:/opt/datafiles
      - ~/data/nifi/scriptfiles:/opt/scriptfiles
      - ~/data/nifi/certfiles:/opt/certfiles
    ports:
      - "18080:8080"
      - "18081:8081"
      - "18443:8443"

  # Redis Data Container
  reddata:
    image: cogniteev/echo
    command: echo 'Data Container for Redis'
    volumes:
      - ~/data/redis:/data
